- id: doorbel_motion
  alias: doorbell motion
  hide_entity: true
  trigger:
    platform: template
    value_template: '{{ is_state_attr(''sensor.ring_front_door_last_activity'', ''recording_status'',
      ''ready'') }}'
  action:
    service: downloader.download_file
    data_template:
      url: '{{ states.camera.front_door.attributes.video_url }}'
      filename: latest.mp4
      overwrite: true
- id: garage_motion_on
  alias: garage motion on
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion
    to: 'on'
  action:
    service: homeassistant.turn_on
    data:
      entity_id: switch.garage_light
- id: garage_motion_off
  alias: garage motion off
  hide_entity: true
  trigger:
    platform: state
    entity_id: binary_sensor.garage_motion
    to: 'off'
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.garage_light
- id: driveway_lights_on
  alias: driveway lights on
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.all_covers
    to: open
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_on
    data:
      entity_id: switch.driveway_light
- id: driveway_lights_off
  alias: driveway lights off
  hide_entity: true
  trigger:
    platform: state
    entity_id: group.all_covers
    to: closed
  condition:
    condition: state
    entity_id: sun.sun
    state: below_horizon
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.driveway_light
- id: sunset_lights_on
  alias: sunset lights on
  hide_entity: true
  trigger:
    platform: sun
    event: sunset
    offset: -00:30:00
  action:
  - service: homeassistant.turn_on
    data:
      entity_id: switch.porch_light
  - service: homeassistant.turn_on
    data:
      entity_id: light.living_room_lamp
- id: late_night_lights_off
  alias: late night lights off
  hide_entity: true
  trigger:
    platform: time
    at: 00:00:00
  action:
    service: homeassistant.turn_off
    data:
      entity_id: light.living_room_lamp
- id: sunrise_lights_off
  alias: sunrise lights off
  hide_entity: true
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    data:
      entity_id: switch.porch_light
- id: device_alert
  alias: device alert
  trigger:
  - below: 25
    entity_id: group.all_devices
    platform: numeric_state
  - above: '20'
    entity_id: sensor.deep_freezer_temp
    platform: numeric_state
  - above: '20'
    entity_id: sensor.freezer_temp
    platform: numeric_state
  - above: '50'
    entity_id: sensor.drink_fridge_temp
    platform: numeric_state
  action:
  - data_template:
      message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement
        }}.'
    service: notify.phones
  - data_template:
      entity_id: '{{ trigger.to_state.entity_id }}'
      message: ' is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement
        }}.'
      name: '{{ trigger.to_state.name }}'
    service: logbook.log
  hide_entity: true
- id: garage_light_double_off
  alias: garage light double off
  trigger:
  - event_data:
      entity_id: zwave.garage_light
      scene_data: 3
      scene_id: 1
    event_type: zwave.scene_activated
    platform: event
  action:
  - data:
      entity_id: switch.garage_light
    service: homeassistant.turn_off
- id: ios_close_covers
  alias: ios close covers
  trigger:
    platform: event
    event_type: ios.notification_action_fired
    event_data:
      actionName: CLOSE_COVERS
  action:
  - service: cover.close_cover
    data:
      entity_id: group.all_covers
- id: ios_locak_doors
  alias: ios lock doors
  trigger:
  - event_data:
      actionName: LOCK_DOORS
    event_type: ios.notification_action_fired
    platform: event
  action:
  - data:
      entity_id: group.all_locks
    service: lock.lock
