- id: doorbel_motion
  alias: doorbell motion
  trigger:
    platform: state
    entity_id: binary_sensor.ring_front_door_motion
    to: 'off'
  action:
    service: python_script.ring_downloader
- id: garage_motion_on
  alias: garage motion on
  trigger:
    platform: state
    entity_id: sensor.garage_motion_sensor
    to: 'on'
  action:
    service: homeassistant.turn_on
    entity_id: switch.garage_light
- id: garage_motion_off
  alias: garage motion off
  trigger:
    platform: state
    entity_id: sensor.garage_motion_sensor
    to: 'off'
  action:
    service: homeassistant.turn_off
    entity_id: switch.garage_light
- id: driveway_lights_on
  alias: driveway lights on
  trigger:
    platform: state
    entity_id: group.all_covers
    to: 'open'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_on
    entity_id: switch.driveway_light
- id: driveway_lights_off
  alias: driveway lights off
  trigger:
    platform: state
    entity_id: group.all_covers
    to: 'closed'
  condition:
    condition: state
    entity_id: sun.sun
    state: 'below_horizon'
  action:
    service: homeassistant.turn_off
    entity_id: switch.driveway_light
- id: sunset_lights_on
  alias: sunset lights on
  trigger:
    platform: sun
    event: sunset
    offset: '-00:30:00'
  action:
    service: homeassistant.turn_on
    entity_id: switch.porch_light, light.living_room_lamp
- id: late_night_lights_off
  alias: late night lights off
  trigger:
    platform: time
    at: '00:00:00'
  action:
    service: homeassistant.turn_off
    entity_id: light.living_room_lamp
- id: sunrise_lights_off
  alias: sunrise lights off
  trigger:
    platform: sun
    event: sunrise
  action:
    service: homeassistant.turn_off
    entity_id: switch.porch_light

- id: device_low_battery
  alias: device low battery
  trigger:
    platform: numeric_state
    entity_id: group.all_devices
    below: 25
  action:
    - service: notify.phones
      data_template:
        message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'
    - service: logbook.log
      data_template:
        name: '{{ trigger.to_state.name }}'
        entity_id: '{{ trigger.to_state.entity_id }}'
        message: ' is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'

- id: freezer_temp_alert
  alias: freezer temp alert
  trigger:
    platform: numeric_state
    entity_id: sensor.deep_freezer_temp, sensor.freezer_temp
    above: 20
  action:
    - service: notify.phones
      data_template:
        message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'
    - service: logbook.log
      data_template:
        name: '{{ trigger.to_state.name }}'
        entity_id: '{{ trigger.to_state.entity_id }}'
        message: ' is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'
- id: fridge_temp_alert
  alias: fridge temp alert
  trigger:
    platform: numeric_state
    entity_id: sensor.drink_fridge_temp
    above: 50
  action:
    - service: notify.phones
      data_template:
        message: '{{ trigger.to_state.name }} is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'
    - service: logbook.log
      data_template:
        name: '{{ trigger.to_state.name }}'
        entity_id: '{{ trigger.to_state.entity_id }}'
        message: ' is {{ trigger.to_state.state }}{{ trigger.to_state.attributes.unit_of_measurement }}.'

