- platform: ring
  monitored_conditions:
    - ding
    - motion

- platform: template
  sensors:
    doors_closed:
      friendly_name: 'Doors & Windows Closed'
      device_class: opening
      value_template: >-
        {{ is_state('binary_sensor.main_doors', 'off')
          and is_state('binary_sensor.back_door', 'off')
          and is_state('binary_sensor.master_windows', 'off')
          and is_state('binary_sensor.upstairs_windows', 'off')
          and is_state('binary_sensor.downstairs_windows', 'off') }}
      entity_id:
        - binary_sensor.main_doors
        - binary_sensor.back_door
        - binary_sensor.master_windows
        - binary_sensor.upstairs_windows
        - binary_sensor.downstairs_windows
    covers_closed:
      friendly_name: 'Garages & Gate Closed'
      device_class: opening
      value_template: >-
        {{ is_state('cover.gate', 'closed')
          and is_state('cover.double_garage', 'closed')
          and is_state('cover.single_garage', 'closed') }}
      entity_id:
        - cover.gate
        - cover.double_garage
        - cover.single_garage
    doors_locked:
      friendly_name: 'Doors Locked'
      value_template: >-
        {{ is_state('lock.front_door_lock', 'locked')
          and is_state('lock.back_door_lock', 'locked')
          and is_state('lock.garage_door_lock', 'locked') }}
      entity_id:
        - lock.front_door_lock
        - lock.back_door_lock
        - lock.garage_door_lock
    alarm_armed:
      friendly_name: 'Alarm Armed'
      value_template: "{{ is_state('alarm_control_panel.home_alarm', 'armed_away') or is_state('alarm_control_panel.home_alarm', 'pending') }}"
      entity_id:
        - alarm_control_panel.home_alarm
