- platform: rachio

- platform: ring

- platform: template
  sensors:
    doors_closed:
      friendly_name: 'Doors & Windows Closed'
      device_class: moving
      value_template: >-
        {{ states('binary_sensor.main_doors') == 'off'
          and states('binary_sensor.back_door') == 'off'
          and states('binary_sensor.master_windows') == 'off'
          and states('binary_sensor.downstairs_windows') == 'off'
          and states('binary_sensor.upstairs_windows') == 'off' }}
      entity_id:
        - binary_sensor.main_doors
        - binary_sensor.back_door
        - binary_sensor.master_windows
        - binary_sensor.downstairs_windows
        - binary_sensor.upstairs_windows
