homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_altitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "switch.*_light":
      icon: mdi:lightbulb

alert: !include alert.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensor.yaml

config:

conversation:

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster
  - platform: template
    covers:
      gate:
        friendly_name: 'Gate'
        value_template: "{{ is_state('binary_sensor.gate_closed_sensor', 'off') }}"
        entity_id: binary_sensor.gate_closed_sensor
        open_cover:
          service: script.gate_open
        close_cover:
          service: script.gate_close
        stop_cover:
          service: script.gate_stop

device_tracker:
  - platform: owntracks
    max_gps_accuracy: 200
    waypoints: False
    track_new_devices: False
  - platform: unifi
    host: unifi.local
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: False
    track_new_devices: False

discovery:
  ignore:
    - directv
    - samsung_tv

ecobee:
  api_key: !secret ecobee_key
  hold_temp: False

emulated_hue:
  type: alexa
  upnp_bind_multicast: False
  exposed_domains:
    - scene
    - script
    - switch
    - light
    - cover
    - lock

envisalink: !include envisalink.yaml

frontend:

group: !include group.yaml

history:
  exclude:
    domains:
      - automation
      - group

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  trusted_networks:
    - 127.0.0.0/8
    - 192.168.0.0/16
  ip_ban_enabled: True
  login_attempts_threshold: 5

influxdb:
  host: metrics.local
  username: !secret influxdb_username
  password: !secret influxdb_password

ios:

isy994:
  host: http://isy.local:80
  username: !secret isy_username
  password: !secret isy_password
  sensor_string: 'Sensor'
  hidden_string: '~'

logbook:
  exclude:
    domains:
      - group

logger:
  default: info
  logs:
    plexapi: warn
    homeassistant.components.http: warn

media_player:
  - platform: plex

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

notify: !include notify.yaml

recorder:
  purge_days: 7

remote:
  - platform: harmony
    name: 'Media Room'
    activity: 'Watch Media'

ring:
  username: !secret ring_username
  password: !secret ring_password

scene: !include scene.yaml

script: !include script.yaml

sensor: !include sensor.yaml

sun:

updater:
  include_used_components: true

zone: !include zone.yaml
