homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 580
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

automation: !include automation.yaml

binary_sensor: !include binary_sensor.yaml

conversation:

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200

#discovery:

ecobee:
  api_key: !secret ecobee_key
  hold_temp: False

emulated_hue:
  exposed_domains:
    - switch
    - light
    - cover
    - lock

envisalink: !include envisalink.yaml

frontend:

graphite:
  host: 192.168.1.16
  port: 2003

group: !include group.yaml

history:

http:
  api_password: !secret api_password
  ssl_certificate: /home/hass/.homeassistant/certs/bryce_net.crt
  ssl_key: /home/hass/.homeassistant/certs/bryce_net.key

ifttt:
  key: !secret ifttt_key

isy994:
  host: http://isy.local:80
  username: !secret isy_username
  password: !secret isy_password
  hidden_string: '{HIDE}'

logbook:

logger:
  default: info
  logs:
    plexapi: warn

media_player:
  - platform: plex
#  - platform: directv
#    host: 192.168.1.140
#    name: DirecTV DVR
#  - platform: samsungtv
#    host: 192.168.1.141
#    port: 8001
#    name: Living Room TV
#  - platform: directv
#    host: 192.168.1.142
#    name: Living Room DirecTV
#  - platform: samsungtv
#    host: 192.168.1.143
#    name: Master Bedroom TV

#modbus:
#  type: tcp
#  host: temp.local
#  port: 502

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  keepalive: 60
  username: !secret mqtt_username
  password: !secret mqtt_password
  protocol: 3.1

notify: !include notify.yaml

recorder:
  purge_days: 30

scene: !include scene.yaml

script: !include script.yaml

sensor: !include sensor.yaml

sun:

updater:

zeroconf:

#zone: !include zone.yaml

#zwave:
#  usb_path: /dev/cuaU0
#  config_path: /usr/local/home-assistant/lib/python3.4/site-packages/libopenzwave-0.3.1-py3.4-freebsd-11.0-RELEASE-amd64.egg/config

