homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_altitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob: !include customize_glob.yaml

ambient_station:
  api_key: !secret ambient_api_key
  app_key: !secret ambient_app_key

alert: !include alert.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensor.yaml

camera:
  - platform: ring

cloud:

config:

conversation:

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster
  - platform: template
    covers:
      gate:
        friendly_name: 'Gate'
        value_template: "{{ is_state('binary_sensor.gate_closed', 'off') }}"
        entity_id: binary_sensor.gate_closed
        open_cover:
          service: script.gate_open
        close_cover:
          service: script.gate_close

device_tracker:
  - platform: owntracks
    new_device_defaults:
      track_new_devices: false
  - platform: unifi
    host: !secret unifi_host
    verify_ssl: false
    username: !secret unifi_username
    password: !secret unifi_password
    scan_interval: 60

discovery:
  ignore:
    - directv
    - samsung_tv

downloader:
  download_dir: downloads

ecobee:
  api_key: !secret ecobee_key

envisalink: !include envisalink.yaml

ffmpeg:

frontend:

google_assistant:
  project_id: hass
  api_key: !secret google_api_key

history:
  exclude:
    domains:
      - automation
      - group

http:
  base_url: https://home.bryce.net:8123
  ssl_certificate: /ssl/fullchain.pem
  ssl_key: /ssl/privkey.pem
  trusted_networks:
    - 127.0.0.1
    - ::1
    - 10.0.0.0/8
    - 172.16.0.0/12
    - 192.168.0.0/16
  ip_ban_enabled: true
  login_attempts_threshold: 5

influxdb:
  host: !secret influxdb_host
  username: !secret influxdb_username
  password: !secret influxdb_password
  tags_attributes:
    - friendly_name

ios:
  push:
    categories:
      - name: Covers
        identifier: 'covers'
        actions:
          - identifier: 'CLOSE_COVERS'
            title: 'Close'
      - name: Locks
        identifier: 'locks'
        actions:
          - identifier: 'LOCK_DOORS'
            title: 'Lock Doors'

logbook:
  exclude:
    domains:
      - group

logger:
  default: info
  logs:
    engineio.client: warn
    homeassistant.components.http: warn
    socketio.client: warn

map:

notify: !include notify.yaml

openuv:
  api_key: !secret openuv_api_key

owntracks:
  max_gps_accuracy: 200

rachio:
  api_key: !secret rachio_api_key

recorder:
  purge_keep_days: 1

remote:
  - platform: harmony
    name: 'Media Room'
    activity: 'Watch Media'

ring:
  username: !secret ring_username
  password: !secret ring_password

scene: !include scene.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

sun:

switch: !include switch.yaml

system_health:

updater:
  include_used_components: true

zwave:
  network_key: !secret network_key
  device_config:
    sensor.gate:
      ignored: true
  device_config_glob:
    "sensor.*_alarm_level":
      ignored: true
    "sensor.*_alarm_type":
      ignored: true
    "sensor.*_sourcenodeid":
      ignored: true

#zha:
#  usb_path: /dev/ttyAMA0
#  database_path: /config/zigbee.db

zone: !include zone.yaml
