homeassistant:
  name: Home
  latitude: !secret home_latitude
  longitude: !secret home_longitude
  elevation: !secret home_altitude
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml
  customize_glob:
    "switch.*_light":
      icon: mdi:lightbulb

alert: !include alert.yaml

automation: !include automations.yaml

binary_sensor: !include binary_sensor.yaml

camera:
  - platform: ring

cloud:
  alexa:
    filter:
      exclude_entities:
        - script.gate_stop
        - switch.auto_dr
        - switch.garage_tamper_alarm
        - switch.gate_power_management
        - switch.gate_pulse_meter
        - switch.gate_switch
        - switch.master_closet_multilevel

config:

conversation:

cover:
  - platform: myq
    username: !secret myq_username
    password: !secret myq_password
    type: liftmaster
  - platform: template
    covers:
      gate:
        friendly_name: 'Gate'
        value_template: "{{ is_state('binary_sensor.gate_closed_sensor', 'off') }}"
        entity_id: binary_sensor.gate_closed_sensor
        open_cover:
          service: script.gate_open
        close_cover:
          service: script.gate_close
        stop_cover:
          service: script.gate_stop

device_tracker:
  - platform: unifi
    host: unifi.local
    username: !secret unifi_username
    password: !secret unifi_password
    verify_ssl: false
    track_new_devices: false
    scan_interval: 60
  - platform: owntracks_http

discovery:
  ignore:
    - directv
    - samsung_tv

downloader:
  download_dir: downloads

ecobee:
  api_key: !secret ecobee_key
  hold_temp: false

emulated_hue:
  upnp_bind_multicast: false
  exposed_domains:
    - switch
    - light
    - scene
    - script

envisalink: !include envisalink.yaml

ffmpeg:
  ffmpeg_bin: '/usr/local/bin/ffmpeg'

frontend:

group: !include group.yaml

history:
  exclude:
    domains:
      - automation
      - group

http:
  api_password: !secret api_password
  ssl_certificate: !secret ssl_certificate
  ssl_key: !secret ssl_key
  use_x_forwarded_for: true
  ip_ban_enabled: true
  login_attempts_threshold: 5
  trusted_networks:
    - 127.0.0.0/8
    - 192.168.0.0/16

influxdb:
  host: metrics.local
  username: !secret influxdb_username
  password: !secret influxdb_password
  tags_attributes:
    - friendly_name

ios:
  push:
    categories:
      - name: Gate
        identifier: 'gate'
        actions:
          - identifier: 'CLOSE_GATE'
            title: 'Close Gate'
      - name: Garage
        identifier: 'garage'
        actions:
          - identifier: 'CLOSE_GARAGE'
            title: 'Close Garage'

isy994:
  host: http://isy.local:80
  username: !secret isy_username
  password: !secret isy_password
  sensor_string: 'Sensor'
  ignore_string: '~'

logbook:
  exclude:
    domains:
      - group

logger:
  default: info
  logs:
    homeassistant.components.http: warn

notify: !include notify.yaml

python_script:

rachio:
  api_key: !secret rachio_api_key

recorder:
  purge_interval: 1
  purge_keep_days: 7

remote:
  - platform: harmony
    name: 'Media Room'
    activity: 'Watch Media'
    scan_interval: 60

#usps:
#  username: !secret usps_username
#  password: !secret usps_password

ring:
  username: !secret ring_username
  password: !secret ring_password

scene: !include scene.yaml

script: !include scripts.yaml

sensor: !include sensor.yaml

sun:

#switch:
#  - platform: rachio
#    access_token: !secret rachio_api_key
#    entity_namespace: 'sprinkler'
#    scan_interval: 60

updater:
  include_used_components: true

zone: !include zone.yaml
