homeassistant:
  name: Home
  latitude: !secret latitude
  longitude: !secret longitude
  elevation: 580
  unit_system: imperial
  time_zone: America/Chicago
  customize: !include customize.yaml

automation: !include automation.yaml

binary_sensor: !include binary_sensor.yaml

#conversation:

device_tracker:
  platform: owntracks
  max_gps_accuracy: 200
  waypoints: False

#discovery:

ecobee:
  api_key: !secret ecobee_key
  hold_temp: False

emulated_hue:
  type: alexa
  upnp_bind_multicast: False
  exposed_domains:
    - scene
    - script
    - switch
    - light
    - cover
    - lock

envisalink: !include envisalink.yaml

frontend:

graphite:
  host: metrics.local
  port: 2003

group: !include group.yaml

history:
  exclude:
    domains:
      - automation
      - group

http:
  api_password: !secret api_password
  ssl_certificate: /usr/local/etc/letsencrypt/live/home.bryce.net/fullchain.pem
  ssl_key: /usr/local/etc/letsencrypt/live/home.bryce.net/privkey.pem
  trusted_networks:
    - 127.0.0.0/8
    - 192.168.0.0/16
  ip_ban_enabled: True
  login_attempts_threshold: 5

#ifttt:
#  key: !secret ifttt_key

isy994:
  host: http://isy.local:80
  username: !secret isy_username
  password: !secret isy_password
  sensor_string: 'Sensor'
  hidden_string: '~'

logbook:
  exclude:
    domains:
      - group

logger:
  default: info
  logs:
    plexapi: warn

media_player:
  - platform: plex

mqtt:
  broker: localhost
  port: 1883
  client_id: home-assistant
  username: !secret mqtt_username
  password: !secret mqtt_password
  birth_message:
    topic: 'hass/status'
    payload: 'online'
    qos: 1
    retain: true
  will_message:
    topic: 'hass/status'
    payload: 'offline'
    qos: 1
    retain: true

notify: !include notify.yaml

recorder:
  purge_days: 14

remote:
  - platform: harmony
    name: Media Room
    host: 192.168.1.154

scene: !include scene.yaml

script: !include script.yaml

sensor: !include sensor.yaml

sun:

updater:

zone: !include zone.yaml

