- platform: mqtt
  name: 'Bryce Phone Battery'
  state_topic: 'owntracks/bryce/phone'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'

- platform: mqtt
  name: 'Cindy Phone Battery'
  state_topic: 'owntracks/cindy/phone'
  unit_of_measurement: '%'
  value_template: '{{ value_json.batt }}'

- platform: plex
  host: media.local

- platform: nzbget
  host: media.local
  monitored_variables:
    - download_rate
    - remaining_size

- platform: sonarr
  api_key: !secret sonarr_api_key
  host: media.local
  monitored_conditions:
    - upcoming
    - wanted
    - queue
    - commands

- platform: wunderground
  api_key: !secret wunderground_api_key
  pws_id: KTXFRISC82
  monitored_conditions:
    - weather
    - temp_f
    - feelslike_f
    - heat_index_f
    - dewpoint_f
    - relative_humidity
    - visibility_mi
    - wind_string
    - wind_mph
    - wind_dir
    - precip_today_in
    - pressure_in
    - UV
    - solarradiation
    - alerts

- platform: speedtest
  server_id: 4323
  monitored_conditions:
    - download
    - upload
  hour: 6

- platform: rest
  name: temp_values
  resource: 'http://temp.local/stateFull.xml'
  username: !secret temp_username
  password: !secret temp_password
  value_template: '{{ value|replace("<"," <")|striptags() }}'
  scan_interval: 180

- platform: template
  sensors:
    deep_freezer_temp:
      friendly_name: 'Deep Freezer'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[1] }}'
    freezer_temp:
      friendly_name: 'Freezer'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[2] }}'
    drink_fridge_temp:
      friendly_name: 'Drink Fridge'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[3] }}'
    garage_temp:
      friendly_name: 'Garage Temp'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[4] }}'
    media_room_remote:
      friendly_name: 'Family Room'
      value_template: '{{ states.remote.media_room.attributes.current_activity }}'

#- platform: modbus
#  registers:
#    - name: Deep Freezer Temp
#      unit_of_measurement: '°F'
#      register: 16
#      count: 2
#      #scale: 0.01
#    - name: Freezer Temp
#      unit_of_measurement: '°F'
#      register: 18
#      count: 2
#      #scale: 0.01
#    - name: Drink Fridge Temp
#      unit_of_measurement: '°F'
#      register: 20
#      count: 2
#      #scale: 0.01
#    - name: Garage Temp
#      unit_of_measurement: '°F'
#      register: 22
#      count: 2
#      #scale: 0.01
