#
# Z-Wave battery levels
#
- platform: template
  sensors:
    front_door_lock_battery:
      friendly_name: 'Front Door Lock Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.front_door.attributes.battery_level }}'
      entity_id: zwave.front_door
    back_door_lock_battery:
      friendly_name: 'Back Door Lock Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.back_door.attributes.battery_level }}'
      entity_id: zwave.back_door
    garage_door_lock_battery:
      friendly_name: 'Garage Door Lock Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.garage_door.attributes.battery_level }}'
      entity_id: zwave.garage_door
    master_closet_battery:
      friendly_name: 'Master Closet Sensor Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.master_closet.attributes.battery_level }}'
      entity_id: zwave.master_closet
    mailbox_closed_battery:
      friendly_name: 'Mailbox Sensor Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.mailbox_closed.attributes.battery_level }}'
      entity_id: zwave.mailbox_closed
    garage_motion_battery:
      friendly_name: 'Garage Motion Sensor Battery'
      unit_of_measurement: '%'
      value_template: '{{ states.zwave.garage_motion.attributes.battery_level }}'
      entity_id: zwave.garage_motion

#
# Temp Probes
#
- platform: rest
  name: temp_values
  resource: 'http://temp.local/stateFull.xml'
  username: !secret temp_username
  password: !secret temp_password
  value_template: '{{ value|replace("<"," <")|striptags() }}'
  scan_interval: 180

- platform: template
  sensors:
    deep_freezer_temp:
      friendly_name: 'Deep Freezer'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[1] }}'
      entity_id: sensor.temp_values
    freezer_temp:
      friendly_name: 'Freezer'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[2] }}'
      entity_id: sensor.temp_values
    drink_fridge_temp:
      friendly_name: 'Drink Fridge'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[3] }}'
      entity_id: sensor.temp_values
    garage_temp:
      friendly_name: 'Garage Temp'
      unit_of_measurement: '°F'
      value_template: '{{ states("sensor.temp_values").split(" ")[4] }}'
      entity_id: sensor.temp_values
    media_room_remote:
      friendly_name: 'Media Room'
      value_template: '{{ states.remote.media_room.attributes.current_activity }}'
      entity_id: remote.media_room

#
# Weather
#
- platform: mqtt
  name: 'Appearant Temperature'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.appTemp_F | round(1) }}'
- platform: mqtt
  name: 'Outside Temperature'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.outTemp_F | round(1) }}'
- platform: mqtt
  name: 'Wind Chill'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.windchill_F | round(1) }}'
- platform: mqtt
  name: 'Heat Index'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.heatindex_F | round(1) }}'
- platform: mqtt
  name: 'Dewpoint'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.heatindex_F | round(1) }}'
- platform: mqtt
  name: 'Humidity'
  entity_namespace: wx
  unit_of_measurement: '%'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.outHumidity | round(1) }}'
- platform: mqtt
  name: 'Pressure'
  entity_namespace: wx
  unit_of_measurement: 'inHg'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.barometer_inHg | round(2) }}'
- platform: mqtt
  name: 'Cloud Base'
  entity_namespace: wx
  unit_of_measurement: 'ft'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.cloudbase_foot | int }}'
- platform: mqtt
  name: 'Wind Speed'
  entity_namespace: wx
  unit_of_measurement: 'mph'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.windSpeed_mph | round(1) }}'
- platform: mqtt
  name: 'Wind Gusts'
  entity_namespace: wx
  unit_of_measurement: 'mph'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.windGust_mph }}'
- platform: mqtt
  name: 'Wind Direction'
  entity_namespace: wx
  unit_of_measurement: '°'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.windDir | int }}'
- platform: mqtt
  name: 'Rain Rate'
  entity_namespace: wx
  unit_of_measurement: 'in/hr'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.rainRate_inch_per_hour | round(1) }}'
- platform: mqtt
  name: 'Rainfall (today)'
  entity_namespace: wx
  unit_of_measurement: 'in'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.dayRain_in }}'
- platform: mqtt
  name: 'Rainfall (last hour)'
  entity_namespace: wx
  unit_of_measurement: 'in'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.hourRain_in }}'
- platform: mqtt
  name: 'Rainfall (last 24 hours)'
  entity_namespace: wx
  unit_of_measurement: 'in'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.rain24_in }}'
- platform: mqtt
  name: 'UV Index'
  entity_namespace: wx
  state_topic: 'weather/loop'
  value_template: '{{ value_json.UV | round(1) }}'
- platform: mqtt
  name: 'Solar Radiation'
  entity_namespace: wx
  unit_of_measurement: 'W/m^2'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.radiation_Wpm2 | int }}'
- platform: mqtt
  name: 'Inside Temperature'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.inTemp_F | round(1) }}'
- platform: mqtt
  name: 'Inside Dewpoint'
  entity_namespace: wx
  unit_of_measurement: '°F'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.inDewpoint | round(1) }}'
- platform: mqtt
  name: 'Inside Humidity'
  entity_namespace: wx
  unit_of_measurement: '%'
  state_topic: 'weather/loop'
  value_template: '{{ value_json.inHumidity | round(1) }}'


- platform: plex
  host: media.local

- platform: nzbget
  host: media.local
  monitored_variables:
    - download_paused
    - average_download_rate
    - download_rate
    - download_size
    - remaining_size
    - free_disk_space

- platform: sonarr
  api_key: !secret sonarr_api_key
  host: media.local
  urlbase: /tv
  monitored_conditions:
    - upcoming
    - wanted
    - queue

- platform: speedtest
  server_id: 4323
  monitored_conditions:
    - download
    - upload
  hour: 12

- platform: cert_expiry
  host: home.bryce.net
  port: 8123

#- platform: wunderground
#  api_key: !secret wunderground_api_key
#  pws_id: KTXFRISC82
#  monitored_conditions:
#    - weather
#    - temp_f
#    - feelslike_f
#    - heat_index_f
#    - dewpoint_f
#    - relative_humidity
#    - visibility_mi
#    - wind_string
#    - wind_mph
#    - wind_dir
#    - precip_today_in
#    - pressure_in
#    - UV
#    - solarradiation
#    - alerts
