- platform: rachio
  access_token: !secret rachio_api_key
  entity_namespace: 'sprinkler'

- platform: template
  switches:
    close_covers:
      friendly_name: 'Garages & Gate Closed'
      value_template: "{{ is_state('cover.gate','closed') and is_state('cover.double_garage','closed') and is_state('cover.single_garage','closed') }}"
      entity_id:
        - cover.gate
        - cover.double_garage
        - cover.single_garage
      turn_on:
        service: cover.close_cover
        data:
          entity_id: group.all_covers
      turn_off:
        service: cover.close_cover
        data:
          entity_id: group.all_covers
      icon_template: >-
        {% if is_state('cover.gate','closed') and is_state('cover.double_garage','closed') and is_state('cover.single_garage','closed') %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:checkbox-blank-circle-outline
        {% endif %}
    lock_doors:
      friendly_name: 'Doors Locked'
      value_template: "{{ is_state('lock.front_door','locked') and is_state('lock.back_door','locked') and is_state('lock.garage_door','locked') }}"
      entity_id:
        - lock.front_door
        - lock.back_door
        - lock.garage_door
      turn_on:
        service: lock.lock
        data:
          entity_id: group.all_locks
      turn_off:
        service: lock.lock
        data:
          entity_id: group.all_locks
      icon_template: >-
        {% if is_state('lock.front_door','locked') and is_state('lock.back_door','locked') and is_state('lock.garage_door','locked') %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:checkbox-blank-circle-outline
        {% endif %}
    arm_alarm:
      friendly_name: 'Alarm Armed'
      value_template: "{{ is_state('alarm_control_panel.home_alarm','armed_away') or is_state('alarm_control_panel.home_alarm','pending') }}"
      entity_id:
        - alarm_control_panel.home_alarm
      turn_on:
        service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home_alarm
      turn_off:
        service: alarm_control_panel.alarm_arm_home
        data:
          entity_id: alarm_control_panel.home_alarm
      icon_template: >-
        {% if is_state('alarm_control_panel.home_alarm','armed_away') or is_state('alarm_control_panel.home_alarm','pending') %}
          mdi:checkbox-marked-circle
        {% else %}
          mdi:checkbox-blank-circle-outline
        {% endif %}
