title: Home
views:
  - title: Home
    id: home
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        card:
          title: Alerts
        show_empty: false
        state_filter:
          - 'on'
        entities:
          - alert.main_doors_open
          - alert.back_door_open
          - alert.front_door_unlocked
          - alert.back_door_unlocked
          - alert.double_garage_open
          - alert.single_garage_open
          - alert.gate_open
      - type: entities
        title: Status
        show_header_toggle: false
        entities:
          - binary_sensor.doors_closed
          - switch.close_covers
          - switch.lock_doors
          - switch.arm_alarm
          - type: divider
          - script.open_sesame
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.living_room_lamp
      - type: entities
        title: Outside
        show_header_toggle: false
        entities:
          - lock.front_door
          - lock.back_door
          - lock.garage_door
          - type: divider
          - cover.gate
          - cover.double_garage
          - cover.single_garage
          - type: divider
          - switch.porch_light
          - switch.garage_light
          - switch.driveway_light
      - type: entities
        title: Front Door
        show_header_toggle: false
        column_width: 25%
        entities:
          - camera.front_door
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - type: divider
          - sensor.ups
          - sensor.fedex
  - title: Family
    id: family
    icon: mdi:account-multiple
    cards:
      - type: glance
        title: Family
        entities:
          - device_tracker.bryphone
          - device_tracker.cindy_iphone
          - device_tracker.jenny_phone
#          - device_tracker.katy_phone
      - type: entities
        title: Devices
        entities:
          - sensor.bryphone_battery_level
          - sensor.cindy_iphone_battery_level
#          - sensor.jenny_phone_battery
#          - sensor.katy_phone_battery
#          - sensor.ipad_battery
  - title: Media Room
    id: media_room
    icon: mdi:television-classic
    cards:
      - type: entities
        entities:
          - type: call-service
            name: 'Movie Time!'
            icon: mdi:play
            action_name: 'Start'
            service: remote.turn_on
            service_data: 
              entity_id: remote.media_room
              activity: "Watch Media"
          - remote.media_room
          - light.media_room_lights
          - light.media_room_lamp
  - title: Climate
    id: climate
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Downstairs
        entities:
          - climate.downstairs
          - sensor.downstairs_temperature
          - sensor.living_room_temperature
          - sensor.master_bedroom_temperature
          - sensor.office_temperature
          - sensor.downstairs_humidity
          - binary_sensor.living_room_occupancy
          - binary_sensor.downstairs_occupancy
          - binary_sensor.master_bedroom_occupancy
          - binary_sensor.office_occupancy
      - type: entities
        title: Upstairs
        entities:
          - climate.upstairs
          - sensor.upstairs_temperature
          - sensor.jenny_room_temperature
          - sensor.katy_room_temperature
          - sensor.guest_room_temperature
          - sensor.upstairs_humidity
          - binary_sensor.upstairs_occupancy
          - binary_sensor.jenny_room_occupancy
          - binary_sensor.katy_room_occupancy
          - binary_sensor.guest_room_occupancy
      - type: entities
        title: Garage
        entities:
          - sensor.deep_freezer_temp
          - sensor.freezer_temp
          - sensor.drink_fridge_temp
          - sensor.garage_temp
  - title: Weather
    id: weather
    icon: mdi:cloud
    cards:
      - type: entities
        title: Weather
        entities:
          - sun.sun
          - sensor.pws_weather
          - sensor.pws_temp_f
          - sensor.pws_feelslike_f
          - sensor.pws_heat_index_f
          - sensor.pws_dewpoint_f
          - sensor.pws_relative_humidity
          - sensor.pws_visibility_mi
          - sensor.pws_wind_string
          - sensor.pws_wind_mph
          - sensor.pws_wind_dir
          - sensor.pws_precip_today_in
          - sensor.pws_pressure_in
          - sensor.pws_uv
          - sensor.pws_solarradiation
          - sensor.pws_alerts
      - type: entities
        title: Air Quality
        entities:
          - sensor.us_air_pollution_level
          - sensor.us_air_quality_index
          - sensor.us_main_pollutant
          - sensor.allergy_index_forecasted_average
          - sensor.allergy_index_today
          - sensor.allergy_index_tomorrow
          - sensor.cold__flu_forecasted_average
  - title: Sensors
    id: sensors
    icon: mdi:router-wireless
    cards:
      - type: entities
        title: Alarm
        entities:
          - alarm_control_panel.home_alarm
          - sensor.home_alarm_keypad
          - binary_sensor.main_doors
          - binary_sensor.back_door
          - binary_sensor.master_windows
          - binary_sensor.downstairs_windows
          - binary_sensor.upstairs_windows
      - type: entities
        title: Sprinklers
        show_header_toggle: false
        entities:
          - switch.sprinkler_home_in_standby_mode
          - switch.sprinkler_front_flower_bed
          - switch.sprinkler_side_yard_north
          - switch.sprinkler_front_yard_north
          - switch.sprinkler_front_yard_south
          - switch.sprinkler_side_yard_south__garden
          - switch.sprinkler_back_yard
      - type: entities
        title: Z-Wave
        entities:
          - zwave.zwaveme_zme_uzb1_usb_stick
          - zwave.front_door
          - zwave.garage_door
          - zwave.back_door
          - zwave.porch_light
          - zwave.driveway_light
          - zwave.garage_light
          - zwave.garage_motion
          - zwave.master_closet_sensor
          - zwave.living_room_lamp
          - zwave.media_room_lamp
          - zwave.media_room_lights
          - zwave.gate
      - type: entities
        title: Miscellaneous
        entities:
          - sensor.ssl_certificate_expiry
