title: Home
views:
  - title: Home
    id: home
    icon: mdi:home-assistant
    cards:
      - id: 901356273a3e4d83af82d391bed82df9  # Automatically created id
        type: entity-filter
        card:
          title: Alerts
        show_empty: false
        state_filter:
          - on
        entities:
          - alert.main_doors_open
          - alert.back_door_open
          - alert.front_door_unlocked
          - alert.back_door_unlocked
          - alert.double_garage_open
          - alert.single_garage_open
          - alert.gate_open
      - id: bfd20b012b5d42f580026d90ba52d4bd  # Automatically created id
        type: entities
        title: Status
        show_header_toggle: false
        entities:
          - binary_sensor.doors_closed
          - switch.close_covers
          - switch.lock_doors
          - switch.arm_alarm
          - type: divider
          - script.open_sesame
      - id: 89e4ff23cc514591a56144ec8a89abee  # Automatically created id
        type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - light.living_room_lamp
      - id: d01a652b3f6e4f609698e90c68039291  # Automatically created id
        type: entities
        title: Outside
        show_header_toggle: false
        entities:
          - lock.front_door
          - lock.back_door
          - lock.garage_door
          - type: divider
          - cover.gate
          - cover.double_garage
          - cover.single_garage
          - type: divider
          - switch.porch_light
          - switch.garage_light
          - switch.driveway_light
      - id: 047da31ee6c8482cbff1e9c12d5b2440  # Automatically created id
        type: entities
        title: Front Door
        show_header_toggle: false
        column_width: 25%
        entities:
          - camera.front_door
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
  - title: Family
    id: family
    icon: mdi:account-multiple
    cards:
      - id: 278a12eb59c34135bef3797aaf00f785  # Automatically created id
        type: glance
        title: Family
        entities:
          - device_tracker.bryphone
          - device_tracker.cindy_iphone
          - device_tracker.jenny_phone
          - device_tracker.katy_phone
      - id: 92d48f9fbf87491ebb39a38628be76c9  # Automatically created id
        type: entities
        title: Devices
        entities:
          - sensor.bryphone_battery_level
          - sensor.cindy_iphone_battery_level
          - sensor.jenny_phone_battery
          - sensor.katy_phone_battery
  - title: Media Room
    id: media_room
    icon: mdi:television-classic
    cards:
      - id: 2e5e62b0abbb47f7b3e97fdefdcb2f6e  # Automatically created id
        type: entities
        entities:
          - type: call-service
            name: Movie Time!
            icon: mdi:play
            action_name: Start
            service: remote.turn_on
            service_data:
              entity_id: remote.media_room
              activity: Watch Media
          - remote.media_room
          - light.media_room_lights
          - light.media_room_lamp
  - title: Climate
    id: climate
    icon: mdi:thermometer
    cards:
      - id: 9dbace766a2e4c66a7291a9611c88048  # Automatically created id
        type: entities
        title: Downstairs
        entities:
          - climate.downstairs
          - sensor.downstairs_temperature
          - sensor.living_room_temperature
          - sensor.master_bedroom_temperature
          - sensor.office_temperature
          - sensor.downstairs_humidity
          - binary_sensor.living_room_occupancy
          - binary_sensor.downstairs_occupancy
          - binary_sensor.master_bedroom_occupancy
          - binary_sensor.office_occupancy
      - id: 89b001fd64ad430e8446d534ae953d66  # Automatically created id
        type: entities
        title: Upstairs
        entities:
          - climate.upstairs
          - sensor.upstairs_temperature
          - sensor.jenny_room_temperature
          - sensor.katy_room_temperature
          - sensor.guest_room_temperature
          - sensor.upstairs_humidity
          - binary_sensor.upstairs_occupancy
          - binary_sensor.jenny_room_occupancy
          - binary_sensor.katy_room_occupancy
          - binary_sensor.guest_room_occupancy
      - id: 0e0a8b8ceeb842b180083f594c2f4164  # Automatically created id
        type: entities
        title: Garage
        entities:
          - sensor.deep_freezer_temp
          - sensor.freezer_temp
          - sensor.drink_fridge_temp
          - sensor.garage_temp
  - title: Weather
    id: weather
    icon: mdi:cloud
    cards:
      - id: 3fdcb547dc784f7199a033a14b05f6a9  # Automatically created id
        type: entities
        title: Weather
        entities:
          - sun.sun
          - sensor.pws_weather
          - sensor.pws_temp_f
          - sensor.pws_feelslike_f
          - sensor.pws_heat_index_f
          - sensor.pws_dewpoint_f
          - sensor.pws_relative_humidity
          - sensor.pws_visibility_mi
          - sensor.pws_wind_string
          - sensor.pws_wind_mph
          - sensor.pws_wind_dir
          - sensor.pws_precip_today_in
          - sensor.pws_pressure_in
          - sensor.pws_uv
          - sensor.pws_solarradiation
          - sensor.pws_alerts
      - id: 59909e0fa44c4abca6e374412232701e  # Automatically created id
        type: entities
        title: Air Quality
        entities:
          - binary_sensor.protection_window
          - sensor.current_uv_level
          - sensor.current_uv_index
          - sensor.max_uv_index
          - sensor.current_ozone_level
          - sensor.skin_type_1_safe_exposure_time
          - sensor.skin_type_2_safe_exposure_time
          - sensor.skin_type_3_safe_exposure_time
          - sensor.skin_type_4_safe_exposure_time
          - sensor.skin_type_5_safe_exposure_time
          - sensor.skin_type_6_safe_exposure_time
          - type: divider
          - sensor.allergy_index_forecasted_average
          - sensor.allergy_index_today
          - sensor.allergy_index_tomorrow
          - sensor.cold__flu_forecasted_average
  - title: Sensors
    id: sensors
    icon: mdi:router-wireless
    cards:
      - id: 9e178319a13448669116a70f20d57e2b  # Automatically created id
        type: entities
        title: Alarm
        entities:
          - alarm_control_panel.home_alarm
          - sensor.home_alarm_keypad
          - binary_sensor.main_doors
          - binary_sensor.back_door
          - binary_sensor.master_windows
          - binary_sensor.downstairs_windows
          - binary_sensor.upstairs_windows
      - id: 33813606e3d24dd188f70b7c86dc8bbb  # Automatically created id
        type: entities
        title: Sprinklers
        show_header_toggle: false
        entities:
          - switch.sprinkler_home_in_standby_mode
          - switch.sprinkler_front_flower_bed
          - switch.sprinkler_side_yard_north
          - switch.sprinkler_front_yard_north
          - switch.sprinkler_front_yard_south
          - switch.sprinkler_side_yard_south__garden
          - switch.sprinkler_back_yard
      - id: 2ce2e0dd45fb4062ae58cd82a9610eb0  # Automatically created id
        type: entities
        title: Z-Wave
        entities:
          - zwave.zwaveme_zme_uzb1_usb_stick
          - zwave.front_door
          - zwave.garage_door
          - zwave.back_door
          - zwave.porch_light
          - zwave.driveway_light
          - zwave.garage_light
          - zwave.garage_motion
          - zwave.master_closet_sensor
          - zwave.living_room_lamp
          - zwave.media_room_lamp
          - zwave.media_room_lights
          - zwave.gate
      - id: eabacfceade444afa51221cee5c9b63a  # Automatically created id
        type: entities
        title: Miscellaneous
        entities:
          - sensor.ssl_certificate_expiry
