resources:
  - url: /local/monster-card.js?v=1
    type: js

title: Home
views:
  - title: Home
    id: home
    icon: mdi:home-assistant
    cards:
      - type: entity-filter
        title: Alerts
        show_empty: False
        entities:
          - alert.main_doors_open
          - alert.back_door_open
          - alert.front_door_unlocked
          - alert.back_door_unlocked
          - alert.double_garage_open
          - alert.single_garage_open
          - alert.gate_open
        state_filter:
          - On
      - type: entities
        title: Activities
        entities:
          - script.open_sesame
      - type: entities
        title: Status
        entities:
          - binary_sensor.doors_closed
          - binary_sensor.covers_closed
          - binary_sensor.doors_locked
          - entity: binary_sensor.alarm_armed
            icon: mdi:lock
          - entity: scene.close_covers
            name: 'Close Garages & Gate'
          - entity: scene.lock_doors
            icon: mdi:lock
          - type: call-service
            name: 'Arm Alarm'
            icon: mdi:lock
            action_name: 'Arm'
            service: alarm_control_panel.alarm_arm_home
            service_data: 
              entity_id: alarm_control_panel.home_alarm
      - type: entities
        title: Front
        show_header_toggle: false
        entities:
          - lock.front_door
          - entity: switch.porch_light
            icon: mdi:lightbulb
          - binary_sensor.ring_front_door_ding
          - binary_sensor.ring_front_door_motion
          - sensor.ups
          - sensor.fedex
          - sensor.usps_mail
          - sensor.usps_packages
          - camera.usps_mail
      - type: entities
        title: Garage
        show_header_toggle: false
        entities:
          - lock.garage_door
          - cover.double_garage
          - cover.single_garage
          - entity: switch.garage_light
            icon: mdi:lightbulb
          - binary_sensor.garage_motion
      - type: entities
        title: Back
        show_header_toggle: false
        entities:
          - lock.back_door
          - cover.gate
          - binary_sensor.gate_closed
          - entity: switch.driveway_light
            icon: mdi:lightbulb
      - type: entities
        title: Lights
        show_header_toggle: false
        entities:
          - entity: light.living_room_lamp
            icon: mdi:lightbulb
  - title: Family
    id: family
    icon: mdi:account-multiple
    cards:
      - type: glance
        title: People
        entities:
          - device_tracker.bryphone
          - device_tracker.cindy_iphone
          - device_tracker.jenny_phone
          - device_tracker.katy_phone
      - type: entities
        title: Devices
        entities:
          - sensor.bryphone_battery_level
          - sensor.cindy_iphone_battery_level
          - sensor.jenny_phone_battery
          - sensor.katy_phone_battery
          - sensor.ipad_battery_level
  - title: Media Room
    id: media_room
    icon: mdi:television-classic
    cards:
      - type: entities
        entities:
          - type: call-service
            name: 'Movie Time!'
            icon: mdi:play
            action_name: 'Start'
            service: remote.turn_on
            service_data: 
              entity_id: remote.media_room
              activity: "Watch Media"
          - remote.media_room
          - entity: light.media_room_lights
            icon: mdi:lightbulb
          - entity: light.media_room_lamp
            icon: mdi:lightbulb
  - title: Climate
    id: climate
    icon: mdi:thermometer
    cards:
      - type: entities
        title: Downstairs Climate
        entities:
          - climate.downstairs
          - sensor.downstairs_temperature
          - sensor.living_room_temperature
          - sensor.master_bedroom_temperature
          - sensor.office_temperature
          - sensor.downstairs_humidity
          - binary_sensor.living_room_occupancy
          - binary_sensor.downstairs_occupancy
          - binary_sensor.master_bedroom_occupancy
          - binary_sensor.office_occupancy
      - type: entities
        title: Upstairs Climate
        entities:
          - climate.upstairs
          - sensor.upstairs_temperature
          - sensor.jenny_room_temperature
          - sensor.katy_room_temperature
          - sensor.guest_room_temperature
          - sensor.upstairs_humidity
          - binary_sensor.upstairs_occupancy
          - binary_sensor.jenny_room_occupancy
          - binary_sensor.katy_room_occupancy
          - binary_sensor.guest_room_occupancy
      - type: entities
        title: Garage Climate
        entities:
          - sensor.deep_freezer_temp
          - sensor.freezer_temp
          - sensor.drink_fridge_temp
          - sensor.garage_temp
  - title: Weather
    id: weather
    icon: mdi:cloud
    cards:
      - type: glance
        entities:
          - sun.sun
      - type: entities
        title: Weather Underground
        entities:
          - sensor.pws_weather
          - sensor.pws_temp_f
          - sensor.pws_feelslike_f
          - sensor.pws_heat_index_f
          - sensor.pws_dewpoint_f
          - sensor.pws_relative_humidity
          - sensor.pws_visibility_mi
          - sensor.pws_wind_string
          - sensor.pws_wind_mph
          - sensor.pws_wind_dir
          - sensor.pws_precip_today_in
          - sensor.pws_pressure_in
          - sensor.pws_uv
          - sensor.pws_solarradiation
          - sensor.pws_alerts
      - type: entities
        title: Air Quality
        entities:
          - sensor.us_air_pollution_level
          - sensor.us_air_quality_index
          - sensor.us_main_pollutant
          - sensor.allergy_index_forecasted_average
          - sensor.allergy_index_today
          - sensor.allergy_index_tomorrow
          - sensor.cold__flu_forecasted_average
  - title: Sensors
    id: sensors
    icon: mdi:router-wireless
    cards:
      - type: entities
        title: Alarm
        entities:
          - alarm_control_panel.home_alarm
          - sensor.home_alarm_keypad
          - binary_sensor.main_doors
          - binary_sensor.back_door
          - binary_sensor.master_windows
          - binary_sensor.downstairs_windows
          - binary_sensor.upstairs_windows
      - type: entities
        title: Sprinklers
        show_header_toggle: false
        entities:
          - switch.sprinkler_home_in_standby_mode
          - switch.sprinkler_front_flower_bed
          - switch.sprinkler_side_yard_north
          - switch.sprinkler_front_yard_north
          - switch.sprinkler_front_yard_south
          - switch.sprinkler_side_yard_south__garden
          - switch.sprinkler_back_yard
      - type: custom:monster-card
        show_empty: false
        card:
          type: entities
        filter:
          include:
            - domain: zwave
      - type: entities
        title: Miscellaneous
        entities:
          - sensor.ssl_certificate_expiry
